language: node_js
node_js:
  - 14.2.0
cache:
  directories: [node_modules]
services:
  - docker
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
install:
  - npm install
before_script:
  - docker-compose up -d
script:
  - yarn build
deploy:
  provider: heroku
  api_key:
    secure: 2fc58d86-b4a2-477c-9e86-4fce48304d89
  skip-cleanup: true
  app:
    master: onloadapi
