language:
  node_js
node_js:
  - 14.2.0
cache:
  npm

services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

install:
  - npm ci

before_script:
  - psql -c 'create database nestjs_api;' -U postgres

script:
  - ts-node ./node_modules/typeorm/cli.js migration:run
  - npm start

deploy:
  provider:
    pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
